openapi: 3.0.0
info:
  title: Order API
  description: API to query order information
  version: 1.0.0

paths:
  /v1/customers/{customerId}/orders:
    get:
      summary: Get orders for a specific customer
      description: Returns a list of orders for a specific customer with basic information.
      operationId: getOrdersByCustomer
      tags:
        - Order
      parameters:
        - name: customerId
          in: path
          description: ID of the customer to retrieve orders for
          required: true
          schema:
            type: integer
        - name: page
          in: query
          description: Page number to retrieve
          required: false
          schema:
            type: integer
            default: 0
            minimum: 0
        - name: size
          in: query
          description: Number of results per page
          required: false
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 100
      responses:
        '200':
          description: Paginated list of orders for the customer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetOrdersByCustomerPage'
        '400':
          description: Invalid request

components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          description: Order ID
        customerId:
          type: integer
          description: Customer ID associated with the order
        total:
          type: number
          format: double
          description: Total value of the order
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
    OrderItem:
      type: object
      properties:
        product:
          type: string
          description: Product name
        quantity:
          type: integer
          description: Quantity of the product in the order
        price:
          type: number
          format: double
          description: Unit price of the product
    Pageable:
      type: object
      properties:
        sort:
          $ref: '#/components/schemas/Sort'
        offset:
          type: integer
          description: Current offset
        pageNumber:
          type: integer
          description: Current page number
        pageSize:
          type: integer
          description: Number of elements per page
        unpaged:
          type: boolean
          description: Indicates if this is a pageable request
        paged:
          type: boolean
          description: Indicates if this is a paged request
    Sort:
      type: object
      properties:
        sorted:
          type: boolean
          description: Indicates if sorting is enabled
        unsorted:
          type: boolean
          description: Indicates if sorting is not enabled
        empty:
          type: boolean
          description: Indicates if the sort is empty
    GetOrdersByCustomerPage:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/Order'
        pageable:
          $ref: '#/components/schemas/Pageable'
        totalPages:
          type: integer
          description: Total number of pages
        totalElements:
          type: integer
          description: Total number of elements
        last:
          type: boolean
          description: Indicates if this is the last page
        size:
          type: integer
          description: Number of elements per page
        number:
          type: integer
          description: Current page number
        sort:
          $ref: '#/components/schemas/Sort'
        first:
          type: boolean
          description: Indicates if this is the first page
        numberOfElements:
          type: integer
          description: Number of elements currently on this page

tags:
  - name: Order
    description: Operations related to orders
